name: CI

on: [push, pull_request]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            
            - name: Detect Yarn Cache Directory
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Setup Yarn Cache
              uses: actions/cache@v1
              with:
                path: ${{ steps.yarn-cache.outputs.dir }}
                key: yarn-cache-${{ hashFiles('yarn.lock') }}
            - name: Install Javascript Packages
              run: yarn install --silent --ignore-scripts --non-interactive --no-progress
            
            - name: Test Plugins
              run: yarn jest